//
// Created by Тимур on 23.05.2021.
//

#ifndef SEMESTER_WORK_GAUSS_JORDAN_GAUSS_JORDAN_METHOD_HPP
#define SEMESTER_WORK_GAUSS_JORDAN_GAUSS_JORDAN_METHOD_HPP

std::vector<float> gauss ();

#endif  //SEMESTER_WORK_GAUSS_JORDAN_GAUSS_JORDAN_METHOD_HPP


